[admiral]
items = ["left", "padding", "workspaces", "padding", "title", "padding", "right", "bitcoin", "padding", "tasks", "padding", "mail", "padding", "cpu", "padding", "memory", "padding", "battery", "padding", "clock", "padding"]

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[padding]
path = "echo '   '"
static = true

[battery]
path = "$HOME/.scripts/battery.sh"
reload = 3

[mail]
path = "$HOME/.scripts/mail.sh"
reload = 5

[workspaces]
path = "$HOME/.scripts/workspaces.sh"

[title]
path = "zscroll -n -u 'xtitle -s'"

[clock]
path = "date '+%m/%d %H:%M' "
reload = 1

[memory]
path = "$HOME/.scripts/memory.sh"
reload = 0.05

[cpu]
path = "$HOME/.scripts/cpu.sh"
reload = 0.05

[tasks]
path = "$HOME/.scripts/tasks.sh | grep /"
reload = 5

[bitcoin]
path = "$HOME/.scripts/bitcoin.sh"
reload = 20
