[admiral]
items = ["left", "padding", "workspaces", "padding", "title", "right", "network", "padding", "volume", "padding", "battery", "padding", "clock", "padding"]

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[padding]
path = "echo '   '"
static = true

[battery]
path = "$HOME/.scripts/battery.sh"
reload = 3

[network]
path = "$HOME/.scripts/networkname.sh"
reload = 5

[volume]
path = "$HOME/.scripts/volume.sh"
reload = 0.05

[workspaces]
path = "$HOME/.scripts/workspaces.sh"

[title]
path = "xtitle -s | scroller -o -l 60"

[clock]
path = "date '+%D %H:%M' "
reload = 1
