# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/42a13316-4343-4d0b-98d9-fdedd8a6ad92";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AE28-30CF";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/d499f710-532f-4d4d-bb10-dd080a93f95b"; }
  ];

  nix.maxJobs = lib.mkDefault 4;

  hardware = {
    pulseaudio = {
      enable = true;
      support32Bit = true;
    };
    opengl.driSupport32Bit = true;
    facetimehd.enable = true;
    cpu.intel.updateMicrocode = true;
    bluetooth.enable = true;
  };
}
