#! /bin/sh
#  ______     ______     ______   __     __     __    __     ______     ______    
# /\  == \   /\  ___\   /\  == \ /\ \  _ \ \   /\ "-./  \   /\  == \   /\  ___\   
# \ \  __<   \ \___  \  \ \  _-/ \ \ \/ ".\ \  \ \ \-./\ \  \ \  __<   \ \ \____  
#  \ \_____\  \/\_____\  \ \_\    \ \__/".~\_\  \ \_\ \ \_\  \ \_\ \_\  \ \_____\ 
#   \/_____/   \/_____/   \/_/     \/_/   \/_/   \/_/  \/_/   \/_/ /_/   \/_____/ 

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         4
bspc config window_gap          12

bspc config top_padding         45

bsp config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme spiral

bspc rule -a "*Firefox" desktop='^1'

"$HOME/scripts/polybar-init.sh"

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"
